### ISSUE TITLE
 ERROR: System.Xml.XmlElement

### ISSUE THREAD

**Issue by peterwi** [cloudbase/windows-imaging-tools#344]
Hi,
When trying to run create-windows-online-cloud-image.ps1
I get an error - ERROR: System.Xml.XmlElement and the progress just hangs

WindowsInfo: Windows version 10.0.14393.0. PS version 5.1.14393.693

**Comment by ader1990** [comment]
Hello,

@peterwi can you share the full log, if possible?

Thank you,
Adrian Vladu

**Comment by peterwi** [comment]
I'm trying again with -vv
I can't find the log file? Do you know where is it located?

**Comment by ader1990** [comment]
@peterwi did you manage to solve the issue?

Thank you,
Adrian Vladu

**Comment by peterwi** [comment]
@ader1990 
Unfortunately not. Still same error

**Comment by ader1990** [comment]
> I'm trying again with -vv
> I can't find the log file? Do you know where is it located?

The log messages are shown in the PS console for the Hyper-V and in C:\UnattendResources\image-generation-log.txt on the guest VM.

**Comment by lukas-fichtner** [comment]
Hello!
I had the same error and found a solution. It was a configuration error on my windows server.

How to find the real error?
You need to check the output on the Hyper-V VM 
(You can do this by opening Hyper-V Manager and clicking on the VM).

In my case, there was an error with the VM's Internet connection. So I checked the Virtual Switch Manager and changed the external interface there correctly. 
Now it runs as nice as before. Thank you <3

**Comment by ader1990** [comment]
Closing the issue, as there were no more replies from the issue creator.
